---
- name: Back setup
  hosts: all
  become: true
  tasks:
    - name: Install git
      apt: name=git state=present 


    - name: Check if repository exists
      stat:
        path: "/home/vagrant/microservice-app-example"
      register: result
      
    - name: install repository
      git: 
        repo: https://github.com/tefaardila/microservice-app-example.git
        dest: /home/vagrant/microservice-app-example
        clone: yes
      when: not result.stat.exists


    - name: Remove other folders
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/vagrant/microservice-app-example/frontend/
        - /home/vagrant/microservice-app-example/users-api 
        - /home/vagrant/microservice-app-example/auth-api 
        
    
    - name: Add nodejs apt key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    
    - name: Get nodejs
      shell: sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

    - name: Install nodejs 
      apt: 
        name: nodejs
        state: present 

    - name: Repository Python
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: yes
      
    - name: Install python3.6
      apt: name=python state=present

    - name: Install Pip3
      apt: name=python3-pip state=present

    - name: Get and Prepare redis
      shell: curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
      shell: echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
      
    - name: Install redis
      apt: name=redis state=present
  
    - name: Setpup todos-api
      shell: sudo npm install
      args:
        chdir: /home/vagrant/microservice-app-example/todos-api/

    - name: Setpup log mesasage processor
      shell: sudo pip3 install redis
      shell: sudo pip3 install -r requirements.txt
      args:
        chdir: /home/vagrant/microservice-app-example/log-message-processor/

  