---
- name: backend Deployment
  hosts: all
  become: true
  tasks:    

    - name: Deploy users api
      shell: screen -dm bash -c "JWT_SECRET=PRFT SERVER_PORT=8083 java -jar target/users-api-0.0.1-SNAPSHOT.jar; exe sh"
      args:
         chdir: /home/vagrant/microservice-app-example/users-api   

    - name: Deploy authentication api
      shell:  screen -dm bash -c "JWT_SECRET=PRFT AUTH_API_PORT=8000 USERS_API_ADDRESS=http://192.168.33.11:8083 ./auth-api; exe sh"
      args:
         chdir: /home/vagrant/microservice-app-example/auth-api 
    
    - name: deploy todos
      shell: screen -dm bash -c "JWT_SECRET=PRFT TODO_API_PORT=8082 npm start; exe sh"
      args:
         chdir: /home/vagrant/microservice-app-example/todos-api
         
    - name: deploy log message processor
      shell: screen -dm bash -c "REDIS_HOST=127.0.0.1 REDIS_PORT=6379 REDIS_CHANNEL=log_channel python3 main.py; exe sh"
      args:
         chdir: /home/vagrant/microservice-app-example/log-message-processor
    
