---
- name: database setup
  hosts: all
  become: true
  tasks:
    - name: Install git
      apt: name=git state=present 


    - name: Check if repository exists
      stat:
        path: "/home/vagrant/microservice-app-example"
      register: result
      
    - name: install repository
      git: 
        repo: https://github.com/tefaardila/microservice-app-example.git
        dest: /home/vagrant/microservice-app-example
        clone: yes
      when: not result.stat.exists


    - name: Remove other folders
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/vagrant/microservice-app-example/frontend/
        - /home/vagrant/microservice-app-example/users-api 
        - /home/vagrant/microservice-app-example/auth-api 
        - /home/vagrant/microservice-app-example/todos-api/
        - /home/vagrant/microservice-app-example/log-message-processor
        

    - name: Get and Prepare redis
      shell: curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
      shell: echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
      
    - name: Install redis
      apt: name=redis state=present
  